---

- name: create our lets encrypt directories
  file:
    path: "/etc/letsencrypt/{{ item }}"
    state: directory
    group: root
    mode: "0655"
    owner: root
    recurse: yes
  with_items:
    - 'accounts'
    - 'csr'
    - 'keys'
    - 'renewal'
    - 'renewal-hooks/deploy'
    - 'renewal-hooks/post'
    - 'renewal-hooks/pre'
    - 'live'
    - 'archive'

- name: create our lets encrypt script directory
  file:
    path: "/opt/hmpps/{{ item }}"
    state: directory
    group: root
    mode: "0755"
    owner: ec2-user
    recurse: yes
  with_items:
    - 'scripts'

- name: Create letsecrypt renewal script
  template:
    src: "{{ role_path }}/templates/letsencrypt-renew.sh.j2"
    dest: "/opt/hmpps/scripts/letsencrypt-renew.sh"
    owner: "root"
    mode: "0755"
    group: "root"

- name: Create letsecrypt cert backup script
  template:
    src: "{{ role_path }}/templates/letsencrypt-backup.sh.j2"
    dest: "/opt/hmpps/scripts/letsencrypt-backup.sh"
    owner: "root"
    mode: "0755"
    group: "root"

- name: Create letsecrypt cert restore script
  template:
    src: "{{ role_path }}/templates/letsencrypt-restore.sh.j2"
    dest: "/opt/hmpps/scripts/letsencrypt-restore.sh"
    owner: "root"
    mode: "0755"
    group: "root"

#- name: Generate letsencrypt certs
#  shell: "/opt/hmpps/scripts/letsencrypt-renew.sh > /var/log/letsencrypt-bootstrap.log"
#  args:
#    creates: /var/log/letsencrypt-bootstrap.log

#- name: Backup letsencypt certs to s3
#  shell: "/opt/hmpps/scripts/letsencrypt-backup.sh > /var/log/letsencrypt-backup.log"
#  args:
#    creates: /var/log/letsencrypt-backup.log

#- name: Create a cron job to auto-renew/check the SSL cert every 12 hours
#  template:
#    src: "{{ role_path }}/templates/letsencrypt-renew-cron.j2"
#    dest: "/etc/cron.d/letsencrypt-renew"
#    owner: "root"
#    mode: "0644"
#    group: "root"
