---

- name: Create Prod nginx conf
  template:
    src: "{{ role_path }}/templates/prod-nginx.conf.j2"
    dest: "/etc/nginx/conf.d/im-proxy.conf"
    owner: "root"
    mode: "0644"
    group: "root"
  when: env_type == "prod"

- name: Create Stage nginx conf
  template:
    src: "{{ role_path }}/templates/nonprod-nginx.conf.j2"
    dest: "/etc/nginx/conf.d/im-proxy.conf"
    owner: "root"
    mode: "0644"
    group: "root"
  when: env_type == "stage"

- name: Create Dev nginx conf
  template:
    src: "{{ role_path }}/templates/nonprod-nginx.conf.j2"
    dest: "/etc/nginx/conf.d/im-proxy.conf"
    owner: "root"
    mode: "0644"
    group: "root"
  when: env_type == "dev"
